# Generated by Django 3.2.25 on 2025-10-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0004_license_person'),
    ]

    operations = [
    ]
