# Generated by Django 3.2.25 on 2025-10-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0005_auto_20251004_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='validTo',
            field=models.DateField(null=True),
        ),
    ]
